### ISSUE TITLE
Support multi-file packages

### ISSUE THREAD

**Issue by vermiculus** [purcell/package-lint#111]
I know this is a question that's out there already (#110), but I couldn't find an open issue and I'd like to keep track of it (i.e., subscribe to this issue) so I can make corresponding updates to [emake](https://github.com/vermiculus/emake.el/) when appropriate. As of now, I think I'm going to instruct emake to only `package-lint` the root package file with all the headers.

**Comment by vermiculus** [comment]
Related conversation from the above issue:

> I don't think I want to encourage that kind of duplication -- especially things like package.el-sensitive headers like `Package-Requires` and `Version`.

Duplicating headers between all package files seems to ask for that information to become out-of-sync. (I *know* that I would be unable to keep them in sync without some sort of semi-official tooling.)

**Comment by DamienCassou** [comment]
I change the headers across all files using wgrep. I also don't bother specifying all of the package dependencies in every file: only the minimum Emacs version to make package-lint happy.

**Comment by purcell** [comment]
A little update here: I've been working on this (slowly) recently.

My idea would be that if `package-lint` is being run on a file-backed elisp buffer, it would look for a separate "master" package file in the same directory and use that as the source of package dependencies (and package name) for the buffer. Some thoughts around this:

- To find the "master" file, we proceed from the current file name (e.g. `my-package-utils.el`) and look for a corresponding `-pkg.el` file, otherwise we remove a dash-separated portion of the file name and repeat, this time looking for either `my-package.el` or `my-package-pkg.el`, continuing until we find package headers, or run out of shorter-named files to examine (in which case we assume the last non-`pkg` `.el` file encountered is the "master" file).
- An important case is when directories contain things like `my-package-flycheck.el` and `my-package.el`, each of which have package headers. If a package header is found in the current file, then it should be assumed to be the master file. This means that @DamienCassou's policy of putting package headers in all files would cause problems for the proposed mechanism.
- We don't have support for `-pkg.el` files in `package-lint` etc.
- When encountering `-pkg.el` files, we can provide an "info" message that the file is unnecessary for MELPA.
- `flycheck-package` currently doesn't bother to check a file if it doesn't have its own package headers, which would need to change.
- Also regarding `flycheck`/`flymake`, there's likely a small overhead when checking involves reading other files.

Goal would be to be able to be able to run `package-lint`'s batch checker on a bunch of files (either together or individually) and get a list of package issues that take into account the apparent package structure.

An ideal outcome is when @riscy (who is doing an amazing job reviewing MELPA submissions currently) and authors can easily run `package-lint` across all the code in a package and get meaningful feedback. We will even be able to integrate `package-lint` into the MELPA build at this stage.

**Comment by riscy** [comment]
> To find the "master" file, we proceed from the current file name ...

Yeah, this convention looks like it works.  As long as -- as you say -- the contributor isn't putting package headers in multiple files.

On that note, is there value in making it possible to point to the master file with a (local) variable?  The MELPA build could set that variable based on the recipe (possibly making the build robust to packages with multiple headers), and users could set it as well if they really needed to.

> We will even be able to integrate package-lint into the MELPA build at this stage.

This would be huge!

**Comment by DamienCassou** [comment]
> This means that @DamienCassou's policy of putting package headers in all files would cause problems for the proposed mechanism.

that should be the least of your concerns :-). I will adapt my code to make package-lint happy.

>  To find the "master" file...

what do you want to do with the master file? Do you mean that the other files won't be validated? Or do you mean that all files will be checked according to the master file? Currently, I'm quite happy that package-lint checks that all definitions in `mpdel-playlist.el` start with the `mpdel-playlist` prefix even though the master file is `mpdel.el`. Will I have to give up on that feature from package-lint if it's only going to check for the `mpdel` prefix in every file of the package? I would find that sad. I find it quite cool that each file of a project defines a little package on its own: it means I control the dependencies between the files, giving me the possibility to split my package into several smaller ones whenever I want.

**Comment by purcell** [comment]
> On that note, is there value in making it possible to point to the master file with a (local) variable? The MELPA build could set that variable based on the recipe (possibly making the build robust to packages with multiple headers), and users could set it as well if they really needed to.

I'm not sure how much that really helps, but it's a possibility. One thing I'm very carefully avoiding in general is local variables that control `package-lint` behaviour: `package-lint` is a completely static checker, so it will not read any variables declared in a file, and anyway, I really don't want people to be able to configure `package-lint` in any way in order to subvert checks.

> what do you want to do with the master file? Do you mean that the other files won't be validated? Or do you mean that all files will be checked according to the master file? 

The master file will be used to determine the declared dependencies and effective package-wide symbol prefix that are then used in the various `package-lint` checks for the current file.

> Currently, I'm quite happy that package-lint checks that all definitions in `mpdel-playlist.el` start with the `mpdel-playlist` prefix even though the master file is `mpdel.el`. Will I have to give up on that feature from package-lint if it's only going to check for the `mpdel` prefix in every file of the package?

Yes, probably. Most multi-file packages don't use individual namespaces for the various files, in my experience, and I don't think we need to enforce that. Obviously once a file gets "promoted" to be its own package, it needs to be self-consistent in that regard.

> I would find that sad. I find it quite cool that each file of a project defines a little package on its own: it means I control the dependencies between the files, giving me the possibility to split my package into several smaller ones whenever I want.

Yes, it's still a good practice. It's just not necessary for individual files to do this when they're part of a larger multi-file package. We could consider producing a single "info"-level note about this in future, perhaps.

**Comment by alphapapa** [comment]
> > Currently, I'm quite happy that package-lint checks that all definitions in `mpdel-playlist.el` start with the `mpdel-playlist` prefix even though the master file is `mpdel.el`. Will I have to give up on that feature from package-lint if it's only going to check for the `mpdel` prefix in every file of the package?
> 
> Yes, probably. Most multi-file packages don't use individual namespaces for the various files, in my experience, and I don't think we need to enforce that. Obviously once a file gets "promoted" to be its own package, it needs to be self-consistent in that regard.
> 
> > I would find that sad. I find it quite cool that each file of a project defines a little package on its own: it means I control the dependencies between the files, giving me the possibility to split my package into several smaller ones whenever I want.
> 
> Yes, it's still a good practice. It's just not necessary for individual files to do this when they're part of a larger multi-file package. We could consider producing a single "info"-level note about this in future, perhaps.

I recently added GitHub Actions support to https://github.com/alphapapa/makem.sh, which includes testing with `package-lint`.  One of my packages, https://github.com/alphapapa/org-ql, is a multi-file package, so it would be helpful if `package-lint` were smarter about this.  However, I do use per-file prefixes (e.g. `org-ql-search.el` provides symbols starting with `org-ql-search`).  

If this check were changed as described, that file's symbols would still pass, because the package prefix, `org-ql`, is a prefix of the file's prefix, `org-ql-search`.

However, one of the other files, `helm-org-ql.el`, provides Helm support and follows the standard practice of using the `helm-` prefix.  (Of course, I could provide it as a separate package, but at this time, it doesn't seem worth the extra effort on my end and the extra effort for users of having to install another package.)  So if this check were changed as described, that file would always warn about an incorrect prefix, which means I'd never be able to have a clean `package-lint` pass.

And never being able to have a clean linting pass greatly reduces its value in a CI context, because it makes every CI run appear to fail, even if the test phase passes.

So if there's some way to have our cake and eat it too here, that would be great.

**Comment by purcell** [comment]
That *should* absolutely be a separate package though.

**Comment by purcell** [comment]
See #173

**Comment by purcell** [comment]
> My first instinct was to want to ignore the prefix errors, but what is the correct way to structure such a project?

@amake You're setting `package-lint-main-file`? You haven't provided an example of the "complaints from package-lint" but it's not obvious why you should be seeing any with this variable set.

**Comment by amake** [comment]
Sorry, the complaint is that `foo-run` should have the package prefix `foo-core`.

I was not setting `package-lint-main-file`. Thanks for pointing that out. That should do the trick.

**Comment by purcell** [comment]
Closing because this is long finished. 😁
