### ISSUE TITLE
Detect format field numbers

### ISSUE THREAD

**Issue by amake** [purcell/package-lint#135]
The `format` function became able to accept field numbers in placeholders [in Emacs 26.1](https://github.com/emacs-mirror/emacs/blob/a6894cf0c32c0cc50f1a45cb51117ce01446d666/etc/NEWS.26#L562):

> For example, `(format "%2$s %1$s %2$s" "X" "Y")` produces `Y X Y`.

I just found that this was tripping me up in a package of mine. It is detectable e.g. in CI if you build against pre-26.1 *and* are passing a string literal to `format` (the compiler will error out) but it is undetectable until runtime if you e.g. store the format string in a variable and pass the variable to `format`.

I would like to contribute a check for this; how should I go about it? It would be nice to be able to catch the indirect case as well, so my thought is to inspect all strings and see if they have placeholders with field numbers (under the theory that they are unlikely to be found outside of format strings).

**Comment by purcell** [comment]
This is an interesting case, because it's about how specific functions handle specific arguments, which makes it a very low-level check compared to those already included in `package-lint`. However, these are very commonly-used functions (`error` and `message` implicitly allow format strings too).

If you'd like to contribute a check, I'd say it would be enough to look for string-literal args to `format`/`message`/`error` that contain those placeholders. Scanning all strings still wouldn't guarantee that these cases would be caught, so I think that's the "20" part of "80/20" here.
