### ISSUE TITLE
New argument in get-buffer-create in Emacs 28

### ISSUE THREAD

**Issue by meedstrom** [purcell/package-lint#217]
I was told that this is the tool for detecting Emacs 28-isms, so here goes. I recently accidentally used one: `get-buffer-create` takes a new argument as of Emacs 28. Perhaps package-lint should warn about it?

**Comment by purcell** [comment]
That's actually somewhat out of scope for `package-lint` currently, since this tool primarily aims to help you get your package dependencies and overall file structure correct in order to work smoothly in the package ecosystem. 

Issues of usage and function signatures are somewhat too fine-grained to be easily detected by package-lint: doing so with any reliability would involve compiling the source code, so a better solution is to have CI builds with older Emacs versions, and check that byte-compilation works in all the versions you want to support.

**Comment by meedstrom** [comment]
Fair enough, I'll try and get that set up, or develop in Emacs 27. Thanks for the explanation!
