### ISSUE TITLE
Suggest lexical-binding?

### ISSUE THREAD

**Issue by alphapapa** [purcell/package-lint#60]
There are checks for setting `lexical-binding` in the right place, but would it be good to have a check that suggests using it when it's not set at all?

**Comment by purcell** [comment]
I'm not sure this would be desirable.

In the general case, no, because `lexical-binding` in a package which supports Emacs 23.x can lead to subtle bugs due to differences in binding behaviour. And enabling `lexical-binding` *can* break non-lexically-bound code, so it's not always a universally recommendation, even if it can benefit runtime speed and clarity of compilation messages.

So while I can see some benefits to cautiously suggesting `lexical-binding` in packages which are known to require Emacs >= 24, the lack of `lexical-binding` certainly isn't a packaging issue, so I'd say we shouldn't do this.

Thanks for the suggestion, though!
