### ISSUE TITLE
package-lint--check-defs-prefix doesn't have an exception for globalized minor modes

### ISSUE THREAD

**Issue by tomjakubowski** [purcell/package-lint#62]
I'm writing a minor mode, let's call it `sublime-text-mode`. I'd like to provide a globalized version of the minor mode, using the convenience macro [`define-globalized-minor-mode`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html#index-define_002dglobalized_002dminor_002dmode).

```
(define-globalized-minor-mode global-sublime-text-mode
  sublime-text-mode sublime-text-mode)
```

However, package-lint nags me:

```
    55   1 error           "global-sublime-text-mode" doesn't start with package's prefix "sublime-text". (emacs-lisp-package)
```

It's a fairly strong convention for the globalized function of a minor mode `foo-mode` to be named `global-foo-mode`. Could we (or I, since you have much better things to work on :-)) maybe add an exception, either for this specific case (`define-globalized-minor-mode`) or to allow `global-foo-` as a prefix in addition to `foo-`?

**Comment by purcell** [comment]
I'd personally prefer it if authors would just use the `-global-mode` suffix rather than `global-` as a prefix, since this is also relatively common: I've tended to push authors strongly in this direction, and `package-lint` is partly an effort to automate my own package reviews.

But I can't argue that there are a lot of `global-...-mode`s out there, and it's therefore a de-facto convention rather than an absolute one. I'd therefore be happy to accept a PR (with tests, please!) for this specific case.

Note that this exception would have to be specifically for `global-YOUR-PREFIX-.*-mode`, rather than for `global-YOUR-PREFIX.*`.

**Comment by purcell** [comment]
This was done a while back. :-)
