### ISSUE TITLE
Doesn't detect missing dependency headers for cl-lib

### ISSUE THREAD

**Issue by purcell** [purcell/package-lint#90]
If the linted code has `(require 'cl-lib)`, but no `Package-Requires` declaration for either `(emacs "24.3")` or `(cl-lib)`, then no error is reported.

It would be easy enough to add `cl-lib` to `package-lint--libraries-added-alist`, but that would just tell users to depend on a later Emacs version: it wouldn't tell them about the ELPA option. Ideally, a solution for this would handle other core libraries like `seq` for which ELPA versions exist.

**Comment by Fanael** [comment]
Going to implement this later today.

**Comment by Fanael** [comment]
Change of plans, I can't make it at the moment.

**Comment by purcell** [comment]
Ideally we'd also detect the use of `cl-*` functions without the presence of the necessary `Package-Requires` header, though perhaps the real code problem there would be not having inserted `(require 'cl-lib)`... see https://github.com/melpa/melpa/pull/5073

**Comment by zonuexe** [comment]
This problem is happened in this revision.
https://github.com/emacs-php/jetbrains.el/blob/139003077fba36ae63262a6243d9aaf85f3196dd/jetbrains.el

I often check the absence of `require` in the following places, but here `cl-lib` is not pointed out.

<img width="747" alt="2017-10-22 4 53 21" src="https://user-images.githubusercontent.com/822086/31859669-e240d45a-b749-11e7-82fc-5dccbdc08cff.png">

(This snapshot is the revision from that `(require 'f)` has been removed.)

**Comment by purcell** [comment]
This was fixed by #137.
